### ISSUE TITLE
error code 500 when uploading HTML document in live mode

### ISSUE THREAD

**Issue by apeterson-dmigs** [HHS/simpler-grants-pdf-builder#8]
hello,
i uploaded a html document containing a nofo i wanted to publish. i got an error code 500 after uploading the document in .html format. the .html file was exported from a word document. is it an issue with the document itself or is there something else i should do to fix this issue?

**Comment by pcraig3** [comment]
Hello!

Currently, we are uploading the NOFO documents to Google Drive and then exporting them from there. Google does a conversion from Word to a Google Doc, and so our imports assume that we have an 'exported-from-Google' html file. (Our coaches have been using Google Docs for editing and commenting, so it's already part of our workflow.)

2 things here:

- the export from Google Docs is quite a bit cleaner than Word, if that matters at all to you.
- I am working on a new feature so that the NOFO builder will consume Word documents directly (.docx files), and I will ship it Monday or Tuesday of next week, so it's right around the corner.

Until then, you can try the Google Docs export if it's something you have access to, or you can .... wait a few days. 🐢

**Comment by pcraig3** [comment]
Hiya, just thought I would follow up here. 

On Tuesday, [I cut a new version](https://github.com/HHS/simpler-grants-pdf-builder/commit/eb9209eea6fcab04807c789e6a2ca6ebedf64be7) that includes the ability to import `.docx` files directly, so you should be able to try that out locally if you can get the app running. (You will need to run a `poetry install` first.) It will give you a sense of how the NOFO Builder works and how it formats documents. You can't print the PDFs locally, but you will be able to see the HTML generated for a NOFO, which is what we use to generate the PDFs. 

So that's all good.

However, I would like to clarify that we are running this project as a hosted tool and we have a roadmap of features to work through. It's an open-source project, so you can try it out and see how it works under the hood, but our work for the time being is centred around working through the specific features on our roadmap, not on supporting multiple instances of the tool in prod.

**Comment by pcraig3** [comment]
Closing this since it's been active for a long time with no movement. 

At the time of writing, the NOFO Builder accepts:

- Google Documents that have been exported as HTML
- .docx files directly

Note that we are generally working with 'content guides', which are templated documents that outline the structure of a NOFO, so if your document does not look like this, you may not get what you expect.
